'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from './redux/provider'
import { ToastContainer } from 'react-toastify'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
        <ReduxProvider>
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer hideProgressBar />
          {children}
      </body>
    </html>
        </ReduxProvider>
  )
}
